# Generated by Django 5.2.10 on 2026-01-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=100, unique=True)),
                ('grade', models.IntegerField(choices=[(1, '고1'), (2, '고2'), (3, '고3')])),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_text', models.TextField()),
                ('cleaned_latex', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('answer', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preprocessing.mockexamquestion')),
            ],
        ),
    ]
