# Generated by Django 5.2.10 on 2026-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexamquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='solution_assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockexamquestion',
            name='track',
            field=models.CharField(default='common', max_length=20),
        ),
    ]
