# Generated by Django 5.2.10 on 2026-01-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='예: g1_2020_3_common_q1', max_length=100, unique=True)),
                ('grade', models.IntegerField(choices=[(1, '고1'), (2, '고2'), (3, '고3')])),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('subject', models.CharField(blank=True, help_text='고3 선택과목(기하 등)', max_length=50, null=True)),
                ('raw_text', models.TextField(help_text='JSONL에서 가져온 원본(깨진) 텍스트')),
                ('cleaned_latex', models.TextField(blank=True, help_text='Nougat 모델로 수선된 LaTeX 텍스트', null=True)),
                ('score', models.IntegerField(default=0, help_text='배점 (2, 3, 4점)')),
                ('answer', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='C:\x07i\\source\\... 절대 경로 저장', max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parser.mockexamquestion')),
            ],
        ),
    ]
